<a href="https://colab.research.google.com/github/ka5hely/MSSP-6070-Practical-Programming/blob/main/Modules/Week_05/PARTICIPATION_ACTIVITY_Week_5_Merge_two_Pandas_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount('/content/drive')

from google.colab import userdata
import os

github_token = userdata.get('GitHub')
owner = 'ka5hely'
repository = 'MSSP-6070-Practical-Programming'

clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'


!git clone {clone_url}

os.chdir("/content/MSSP-6070-Practical-Programming/Modules/Week_05")
print(f"Changed directory to: {os.getcwd()}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Cloning into 'MSSP-6070-Practical-Programming'...
remote: Enumerating objects: 168, done.
remote: Counting objects: 100% (168/168), done.
remote: Compressing objects: 100% (157/157), done.
remote: Total 168 (delta 69), reused 7 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (168/168), 1.31 MiB | 6.61 MiB/s, done.
Resolving deltas: 100% (69/69), done.
Changed directory to: /content/MSSP-6070-Practical-Programming/Modules/Week_05

In [5]:
# 2b. Read each file into a dataframe

import pandas as pd

aapl = pd.read_csv('aapl.csv')
amzn = pd.read_csv('amzn.csv')
fb = pd.read_csv('fb.csv')
goog = pd.read_csv('goog.csv')
nflx = pd.read_csv('nflx.csv')

         date      open      high       low     close    volume
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766

In [6]:
# 2c. Add a column to each dataframe, called 'ticker'

aapl['ticker'] = 'AAPL'
amzn['ticker'] = 'AMZN'
fb['ticker'] = 'FB'
nflx['ticker'] = 'NFLX'
goog['ticker'] = 'GOOG'

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

In [9]:
# 2d. Append each file together into a single dataframe

faang_df = pd.concat([aapl, amzn, fb, nflx, goog], ignore_index=True)
faang_df

            date       open       high        low      close    volume ticker
0     2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
1     2018-01-03   169.2521   171.2337   168.6929   168.9578  29517899   AAPL
2     2018-01-04   169.2619   170.1742   168.8106   169.7426  22434597   AAPL
3     2018-01-05   170.1448   172.0381   169.7622   171.6751  23660018   AAPL
4     2018-01-08   171.0375   172.2736   170.6255   171.0375  20567766   AAPL
...          ...        ...        ...        ...        ...       ...    ...
1250  2018-12-24   973.9000  1003.5400   970.1100   976.2200   1590328   GOOG
1251  2018-12-26   989.0100  1040.0000   983.0000  1039.4600   2373270   GOOG
1252  2018-12-27  1017.1500  1043.8900   997.0000  1043.8800   2109777   GOOG
1253  2018-12-28  1049.6200  1055.5600  1033.1000  1037.0800   1413772   GOOG
1254  2018-12-31  1050.9600  1052.7000  1023.5900  1035.6100   1493722   GOOG

[1255 rows x 7 columns]

In [11]:
# 2e. Save the results in a CSV file called 'faanf.csv'
faang_df.to_csv('faang.csv', index=False)

In [13]:
# 2f. Use type conversion to change the 'date' column into a 'datetime'
# and the 'volume' column into integers.
# Then sort by 'date' and 'ticker.'

faang = pd.read_csv('faang.csv')

faang = faang.assign(
    date = pd.to_datetime(faang['date']),
    volume = faang['volume'].astype('int')
).sort_values(
    ['date', 'ticker']
)

faang.head()

           date       open       high        low      close    volume ticker
0    2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
251  2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
502  2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
1004 2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
753  2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX

In [14]:
# 2g. Find the seven rows within the highest value for volume.

faang.nlargest(n=7, columns='volume')

          date      open      high       low     close     volume ticker
644 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
555 2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
559 2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
556 2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
182 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
245 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
212 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [18]:
# 2h. Use the melt() method to make the 'date' and 'ticker' key identifiers.
# Melt the remaining columns so that there are not separated.

faang_melt = faang.melt(
    id_vars=['date', 'ticker'],
    value_vars=['open', 'high', 'low', 'close', 'volume'])
faang_melt

           date ticker variable         value
0    2018-01-02   AAPL     open  1.669271e+02
1    2018-01-02   AMZN     open  1.172000e+03
2    2018-01-02     FB     open  1.776800e+02
3    2018-01-02   GOOG     open  1.048340e+03
4    2018-01-02   NFLX     open  1.961000e+02
...         ...    ...      ...           ...
6270 2018-12-31   AAPL   volume  3.500347e+07
6271 2018-12-31   AMZN   volume  6.954507e+06
6272 2018-12-31     FB   volume  2.462531e+07
6273 2018-12-31   GOOG   volume  1.493722e+06
6274 2018-12-31   NFLX   volume  1.350892e+07

[6275 rows x 4 columns]